function(GroupSourcesByFolder target)
  set(SOURCE_GROUP_DELIMITER "/")
  set(last_dir "")
  set(files "")

  get_target_property(sources ${target} SOURCES)

  foreach(file ${sources})
    file(RELATIVE_PATH relative_file "${PROJECT_SOURCE_DIR}" ${file})
    get_filename_component(dir "${relative_file}" PATH)
    if(NOT "${dir}" STREQUAL "${last_dir}")
      if(files)
        source_group("${last_dir}" FILES ${files})
      endif()
      set(files "")
    endif()
    set(files ${files} ${file})
    set(last_dir "${dir}")
  endforeach()

  if(files)
    source_group("${last_dir}" FILES ${files})
  endif()
endfunction()


macro(add_copy_fullfolder_command _folder)
    get_filename_component(_folder_base "${_folder}/."   ABSOLUTE)
    get_filename_component(_folder_name "${_folder}"      NAME)
    
	set(_destination $<TARGET_FILE_DIR:${PROJECT_NAME}>/)
    file(GLOB_RECURSE allfiles RELATIVE "${_folder_base}" "${_folder}/*")
    set(_old_fn_folder "")
    foreach(_fn ${allfiles})
        get_filename_component(_fn_folder "${_destination}/${_fn}" DIRECTORY)
        #if (NOT "${_fn_folder}" STREQUAL "${_old_fn_folder}")
         #   add_custom_command(TARGET ${PROJECT_NAME} POST_BUILD COMMAND ${ARGN} ${CMAKE_COMMAND} -E make_directory ${_fn_folder})
          #  set(_old_fn_folder ${_fn_folder})
        #endif()
        add_custom_command(TARGET ${PROJECT_NAME} POST_BUILD COMMAND ${ARGN} ${CMAKE_COMMAND} -E copy_if_different ${_folder_base}/${_fn}  $<TARGET_FILE_DIR:${PROJECT_NAME}>/${_fn})
    endforeach()
endmacro()

function(QT5_CREATE_TRANSLATION_Exclude_SubFolder _qm_files)
    set(options)
    set(oneValueArgs)
    set(multiValueArgs OPTIONS)

    cmake_parse_arguments(_LUPDATE "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})
    set(_lupdate_files ${_LUPDATE_UNPARSED_ARGUMENTS})
    set(_lupdate_options ${_LUPDATE_OPTIONS})

    set(_my_sources)
    set(_my_tsfiles)
    foreach(_file ${_lupdate_files})
        get_filename_component(_ext ${_file} EXT)
        get_filename_component(_abs_FILE ${_file} ABSOLUTE)
        if(_ext MATCHES "ts")
            list(APPEND _my_tsfiles ${_abs_FILE})
        else()
            list(APPEND _my_sources ${_abs_FILE})
        endif()
    endforeach()
    foreach(_ts_file ${_my_tsfiles})
        if(_my_sources)
          # make a list file to call lupdate on, so we don't make our commands too
          # long for some systems
          get_filename_component(_ts_name ${_ts_file} NAME)
          set(_ts_lst_file "${CMAKE_CURRENT_BINARY_DIR}${CMAKE_FILES_DIRECTORY}/${_ts_name}_lst_file")
          set(_lst_file_srcs)
          foreach(_lst_file_src ${_my_sources})
              set(_lst_file_srcs "${_lst_file_src}\n${_lst_file_srcs}")
          endforeach()

         # get_directory_property(_inc_DIRS INCLUDE_DIRECTORIES)
         # foreach(_pro_include ${_inc_DIRS})
         #     get_filename_component(_abs_include "${_pro_include}" ABSOLUTE)
         #     set(_lst_file_srcs "-I${_pro_include}\n${_lst_file_srcs}")
         # endforeach()

          file(WRITE ${_ts_lst_file} "${_lst_file_srcs}")
        endif()
        add_custom_command(OUTPUT ${_ts_file}
            COMMAND ${Qt5_LUPDATE_EXECUTABLE}
            ARGS ${_lupdate_options} "@${_ts_lst_file}" -ts ${_ts_file}
            DEPENDS ${_my_sources}
            BYPRODUCTS ${_ts_lst_file} VERBATIM)
    endforeach()
    qt5_add_translation(${_qm_files} ${_my_tsfiles})
    set(${_qm_files} ${${_qm_files}} PARENT_SCOPE)
endfunction()

if(NOT QT_NO_CREATE_VERSIONLESS_FUNCTIONS)
    function(qt_create_translation _qm_files)
        if(QT_DEFAULT_MAJOR_VERSION EQUAL 5)
            qt5_create_translation("${_qm_files}" ${ARGN})
        elseif(QT_DEFAULT_MAJOR_VERSION EQUAL 6)
            qt6_create_translation("${_qm_files}" ${ARGN})
        endif()
        set("${_qm_files}" "${${_qm_files}}" PARENT_SCOPE)
    endfunction()
endif()

# 使用 visual leak detector(VLD)来探测内存泄漏
# 需要指定USE_VISUAL_LEAK_DETECTOR为ON， 并且环境变量PATH中存在Visual Leak Detector安装路径。VLD的使用方法为在main()所在cpp #include "vld.h"，编译运行Debug，然[...]
# 如果需要将记录输出到文件，在VLD安装路径编辑vld.ini，编辑"ReportTo = both"，默认输出文件为memory_leak_report.txt。
function(use_visual_leak_detector target)
    if(NOT USE_VISUAL_LEAK_DETECTOR OR NOT CMAKE_BUILD_TYPE STREQUAL "Debug")
        return()
    endif ()
    if(DEFINED ENV{PATH})
        set(path_list )
        if(WIN32)
            string(REPLACE ";" ";" path_list "$ENV{PATH}")
        endif ()
        set(VLD_PATH "")
        set(VLD_FOUND FALSE)
        foreach(path IN LISTS path_list)
            # 检查路径是否包含 "Visual Leak Detector" 且以 "Win64" 结尾
            if(path MATCHES "Visual Leak Detector" AND path MATCHES "Win64$")
                set(VLD_PATH "${path}")
                set(VLD_FOUND TRUE)
                message(STATUS "Found Visual Leak Detector Win64 path: ${VLD_PATH}")
                break()
            endif()
        endforeach()

        if(VLD_FOUND)
            target_include_directories(${target} PRIVATE ${VLD_PATH}/../../include)
            target_link_libraries(${target} debug ${VLD_PATH}/../../lib/Win64/vld.lib)
        else ()
            message(ERROR "Not found Visual Leak Detector Win64 path but USE_VISUAL_LEAK_DETECTOR specified!")
        endif ()
    endif ()
endfunction()

